.TH "Dokumentacja katalogu /home/adam/zad5_2-AdamStypczyc/include" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu /home/adam/zad5_2-AdamStypczyc/include
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBdron\&.hh\fP"
.br
.ti -1c
.RI "plik \fBexample\&.h\fP"
.br
.ti -1c
.RI "plik \fBGraniastoslup\&.hh\fP"
.br
.ti -1c
.RI "plik \fBGraniastoslup6\&.hh\fP"
.br
.ti -1c
.RI "plik \fBlacze_do_gnuplota\&.hh\fP"
.br
.ti -1c
.RI "plik \fBmacierz\&.hh\fP"
.br
.ti -1c
.RI "plik \fBMacierz\&.hh\fP"
.br
.ti -1c
.RI "plik \fBOstroslup\&.hh\fP"
.br
.ti -1c
.RI "plik \fBPlaskowyz\&.hh\fP"
.br
.ti -1c
.RI "plik \fBProstopadloscian\&.hh\fP"
.br
.ti -1c
.RI "plik \fBScena\&.hh\fP"
.br
.ti -1c
.RI "plik \fBsize\&.hh\fP"
.br
.ti -1c
.RI "plik \fBSkarpa\&.hh\fP"
.br
.ti -1c
.RI "plik \fBwektor\&.hh\fP"
.br
.ti -1c
.RI "plik \fBWektor3D\&.hh\fP"
.br
.in -1c
