.TH "/home/adam/zad5_2-AdamStypczyc/include/dron.hh" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/dron.hh
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'Prostopadloscian\&.hh'\fP
.br
\fC#include 'Graniastoslup6\&.hh'\fP
.br
\fC#include 'lacze_do_gnuplota\&.hh'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBdron\fP"
.br
.RI "Klasa dron Deklaracja klasy dron\&. Zawiera ona elementy i metody potrzebne do wykonywania różnych operacji dronie\&. Zawiera ona elementy klasy prostopadloscian i gransiatoslup6\&. "
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
