.TH "Dummy" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dummy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <example\&.h>\fP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBDummy\fP ()"
.br
.ti -1c
.RI "bool \fBdoSomething\fP ()"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
This is a dummy class to demonstrate features of the boiler plate\&. 
.PP
Definicja w linii 6 pliku example\&.h\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Dummy::Dummy ()"
Default constructor for \fBDummy\fP (does nothing)\&. 
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "bool Dummy::doSomething ()"
Returns a bool\&. 
.PP
\fBZwraca\fP
.RS 4
Always True\&. 
.RE
.PP


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
