.TH "/home/adam/zad5_2-AdamStypczyc/include/example.h" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/example.h
.SH SYNOPSIS
.br
.PP
.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBDummy\fP"
.br
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
