.TH "/home/adam/zad5_2-AdamStypczyc/include/Graniastoslup.hh" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/Graniastoslup.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'Macierz\&.hh'\fP
.br
\fC#include 'Wektor3D\&.hh'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBGraniastoslup\fP"
.br
.RI "Klasa \fBGraniastoslup\fP\&. Deklaracja klasy \fBGraniastoslup\fP\&. Zawiera ona elementy i metody potrzebne do wykonywania różnych operacji na graniastoslupach, np\&. prostopadłościanie i graniastosłupie sześciokątnym foremnym\&. Klasa \fBGraniastoslup6\fP i klasa \fBProstopadloscian\fP dziedziczą z tej klasy\&. "
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
