.TH "Graniastoslup6" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graniastoslup6 \- Klasa \fBGraniastoslup6\fP\&. Deklaracja klasy \fBGraniastoslup6\fP\&. Zawiera ona elementy i metody potrzebne do wykonywania różnych operacji na \fBGraniastoslup6\fP, które są w większości dziedziczone z klasy Gransiatoslup\&. Sama w sobie posiada swój konstruktor parametryczny\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Graniastoslup6\&.hh>\fP
.PP
Dziedziczy \fBGraniastoslup\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBGraniastoslup6\fP (\fBWektor3D\fP sro=\fBWektor3D\fP(), double h=15, double r=20, std::string nazwa='\&.\&./datasets/test_gr\&.dat')"
.br
.RI "Konstruktor parametryczny klasy \fBGraniastoslup6\fP Tworzy \fBGraniastoslup6\fP względem punktu srodka\&. "
.in -1c
.SS "Dodatkowe Dziedziczone Składowe"
.SH "Opis szczegółowy"
.PP 
Klasa \fBGraniastoslup6\fP\&. Deklaracja klasy \fBGraniastoslup6\fP\&. Zawiera ona elementy i metody potrzebne do wykonywania różnych operacji na \fBGraniastoslup6\fP, które są w większości dziedziczone z klasy Gransiatoslup\&. Sama w sobie posiada swój konstruktor parametryczny\&. 
.PP
Definicja w linii 8 pliku Graniastoslup6\&.hh\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Graniastoslup6::Graniastoslup6 (\fBWektor3D\fP sro = \fC\fBWektor3D\fP()\fP, double h = \fC15\fP, double r = \fC20\fP, std::string nazwa = \fC'\&.\&./datasets/test_gr\&.dat'\fP)"

.PP
Konstruktor parametryczny klasy \fBGraniastoslup6\fP Tworzy \fBGraniastoslup6\fP względem punktu srodka\&. 
.PP
\fBParametry\fP
.RS 4
\fIsro\fP punkt odpowiadający srodkowi 
.br
\fIh\fP wartość odpowiadająca wysokości rotora, tutaj ustawiona na 15 
.br
\fIr\fP promień okręgu na którym zbudowane są podstawy górne i dolna rotora tutaj ustawiona na 20 
.br
\fInazwa\fP nazwa pliku który przypisujemy danej bryle 
.br
\fItmp\fP pomocznicy Wektor3D dzięki któremu wpisujemy wartosci współrzędnych 
.RE
.PP

.PP
Definicja w linii 22 pliku Graniastoslup6\&.hh\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
