.TH "/home/adam/zad5_2-AdamStypczyc/include/Plaskowyz.hh" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/Plaskowyz.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'Prostopadloscian\&.hh'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBPlaskowyz\fP"
.br
.RI "Klasa \fBPlaskowyz\fP\&. Deklaracja klasy \fBPlaskowyz\fP\&. Zawiera ona elementy i metody potrzebne do wykonywania różnych operacji na \fBPlaskowyz\fP, które są w większości dziedziczone z klasy Gransiatoslup\&. Sama w sobie posiada swój konstruktor parametryczny\&. "
.in -1c
.SS "Definicje"

.in +1c
.ti -1c
.RI "#define \fBSKALA\fP   2"
.br
.in -1c
.SH "Dokumentacja definicji"
.PP 
.SS "#define SKALA   2"

.PP
Definicja w linii 4 pliku Plaskowyz\&.hh\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
