.TH "/home/adam/zad5_2-AdamStypczyc/include/Prostopadloscian.hh" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/Prostopadloscian.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'Graniastoslup\&.hh'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBProstopadloscian\fP"
.br
.RI "Klasa \fBProstopadloscian\fP\&. Deklaracja klasy prostopadłościan\&. Zawiera ona elementy i metody potrzebne do wykonywania różnych operacji na prostopadłościanie, które są w większości dziedziczone z klasy Gransiatoslup\&. Sama w sobie posiada swój konstruktor parametryczny\&. "
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
