.TH "/home/adam/zad5_2-AdamStypczyc/include/Scena.hh" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/Scena.hh
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'dron\&.hh'\fP
.br
\fC#include 'Plaskowyz\&.hh'\fP
.br
\fC#include 'Ostroslup\&.hh'\fP
.br
\fC#include 'Skarpa\&.hh'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBScena\fP"
.br
.RI "Deklaracja klasy \fBScena\fP Łączy wszystko w całość "
.in -1c
.SS "Definicje"

.in +1c
.ti -1c
.RI "#define \fBZAKRES\fP   700"
.br
.RI "Definicje globalne\&. "
.ti -1c
.RI "#define \fBPOCZATEK\fP"
.br
.ti -1c
.RI "#define \fBROZMIAR\fP   15"
.br
.ti -1c
.RI "#define \fBPOLOZENIE_1\fP"
.br
.ti -1c
.RI "#define \fBPOLOZENIE_2\fP"
.br
.ti -1c
.RI "#define \fBPOLOZENIE_3\fP"
.br
.ti -1c
.RI "#define \fBPOLOZENIE_4\fP"
.br
.ti -1c
.RI "#define \fBPOLOZENIE_5\fP"
.br
.ti -1c
.RI "#define \fBPOLOZENIE_6\fP"
.br
.in -1c
.SH "Dokumentacja definicji"
.PP 
.SS "#define POCZATEK"
\fBWartość:\fP
.PP
.nf
    {            \
        0, 0, 0  \
    }
.fi
.PP
Definicja w linii 21 pliku Scena\&.hh\&.
.SS "#define POLOZENIE_1"
\fBWartość:\fP
.PP
.nf
    {                \
        170, 170, 15 \
    }
.fi
.PP
Definicja w linii 26 pliku Scena\&.hh\&.
.SS "#define POLOZENIE_2"
\fBWartość:\fP
.PP
.nf
    {                \
        400, 400, 15 \
    }
.fi
.PP
Definicja w linii 30 pliku Scena\&.hh\&.
.SS "#define POLOZENIE_3"
\fBWartość:\fP
.PP
.nf
    {               \
        400, 200, 0 \
    }
.fi
.PP
Definicja w linii 35 pliku Scena\&.hh\&.
.SS "#define POLOZENIE_4"
\fBWartość:\fP
.PP
.nf
    {               \
        125, 450, 0 \
    }
.fi
.PP
Definicja w linii 39 pliku Scena\&.hh\&.
.SS "#define POLOZENIE_5"
\fBWartość:\fP
.PP
.nf
    {               \
        330, 580, 0 \
    }
.fi
.PP
Definicja w linii 43 pliku Scena\&.hh\&.
.SS "#define POLOZENIE_6"
\fBWartość:\fP
.PP
.nf
    {               \
        550, 550, 0 \
    }
.fi
.PP
Definicja w linii 47 pliku Scena\&.hh\&.
.SS "#define ROZMIAR   15"

.PP
Definicja w linii 25 pliku Scena\&.hh\&.
.SS "#define ZAKRES   700"

.PP
Definicje globalne\&. 
.PP
\fBParametry\fP
.RS 4
\fIZAKRES\fP zakres gnuplota 
.br
\fIPOCZATEK\fP początek siatki 
.br
\fIPOLOZENIE_1\fP położenie startowe drona 0 
.br
\fIPOLOZENIE_2\fP położenie startowe drona 1 
.br
\fIPOLOZENIE_3\fP położenie startowe plaskowyzu 
.br
\fIPOLOZENIE_4\fP położenie startowe ostroslupa 1\&. 
.br
\fIPOLOZENIE_5\fP położenie startowe ostroslupa 2\&. 
.br
\fIPOLOZENIE_6\fP położenie startowe skarpy 
.br
\fIROZMIAR\fP ilość kratek w siatce 
.RE
.PP

.PP
Definicja w linii 20 pliku Scena\&.hh\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
