.TH "/home/adam/zad5_2-AdamStypczyc/include/size.hh" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/size.hh
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "constexpr int \fBSIZE\fP = 2"
.br
.RI "Definicje wartości stałych odpowiadających wielkościom\&. "
.ti -1c
.RI "constexpr int \fBSIZES\fP = 3"
.br
.ti -1c
.RI "constexpr int \fBSZER\fP = 8"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "constexpr int SIZE = 2\fC [constexpr]\fP"

.PP
Definicje wartości stałych odpowiadających wielkościom\&. 
.PP
\fBParametry\fP
.RS 4
\fISIZE\fP wartość równa 2\&. Odpowiadająca wielkością Wektora2D (pozostałość z poprzedniego zadania) 
.br
\fISIZES\fP wartość równa 3\&. Przydatna do deklarowania wielkości tablicy w testach\&. 
.br
\fISZER\fP wartość równa 8\&. Odpowiada ilości wierzchołków prostopadłościanu\&. 
.RE
.PP

.PP
Definicja w linii 8 pliku size\&.hh\&.
.SS "constexpr int SIZES = 3\fC [constexpr]\fP"

.PP
Definicja w linii 9 pliku size\&.hh\&.
.SS "constexpr int SZER = 8\fC [constexpr]\fP"

.PP
Definicja w linii 10 pliku size\&.hh\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
