.TH "/home/adam/zad5_2-AdamStypczyc/include/Wektor3D.hh" 3 "Pn, 14 cze 2021" "Dron 5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adam/zad5_2-AdamStypczyc/include/Wektor3D.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'wektor\&.hh'\fP
.br

.SS "Definicje typów"

.in +1c
.ti -1c
.RI "typedef \fBWektor\fP< double, 3 > \fBWektor3D\fP"
.br
.RI "Deklaracja Wektora3D Deklaracja Wektora3D\&. "
.in -1c
.SH "Dokumentacja definicji typów"
.PP 
.SS "typedef \fBWektor\fP<double, 3> \fBWektor3D\fP"

.PP
Deklaracja Wektora3D Deklaracja Wektora3D\&. 
.PP
Definicja w linii 9 pliku Wektor3D\&.hh\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Dron 5\&.2\&.
