Graniastoslup
std::vector<Wektor3D> Graniastoslup::wspol
Referenced by operator[], translacja, rotacja, zapis, Graniastoslup6::Graniastoslup6, Ostroslup::Ostroslup, Plaskowyz::Plaskowyz, Prostopadloscian::Prostopadloscian, Skarpa::Skarpa.
std::shared_ptr<Wektor3D> Graniastoslup::wymiar
Referenced by Graniastoslup6::Graniastoslup6, Ostroslup::Ostroslup, Plaskowyz::Plaskowyz, Prostopadloscian::Prostopadloscian, Skarpa::Skarpa.
Wektor3D Graniastoslup::srodek
Referenced by ustaw_srodek, pokaz_srodek, translacja, rotacja, zapis, Graniastoslup6::Graniastoslup6, Ostroslup::Ostroslup, Plaskowyz::Plaskowyz, Prostopadloscian::Prostopadloscian, Skarpa::Skarpa.
std::string Graniastoslup::nazwa_pliku
Referenced by ustaw_nazwa, pokaz_nazwa, zapis, Graniastoslup6::Graniastoslup6, Ostroslup::Ostroslup, Plaskowyz::Plaskowyz, Prostopadloscian::Prostopadloscian, Skarpa::Skarpa.
Wektor3D & Graniastoslup::operator[](int i)
Przeciążenie operatora [] set. Umożliwia zmianę wartości poszczególnej wszpółrzędnej graniastoslupa.
Zwraca wektor3D odpowiadający interesującej nas współrzędnej.
References wspol.
const Wektor3D Graniastoslup::operator[](int i) const
Przeciążenie operatora [] get. Umożliwia podgląd wartości poszczególnej wszpółrzędnej graniastoslupa.
Zwraca wektor3D odpowiadający interesującej nas współrzędnej.
References wspol.
void Graniastoslup::ustaw_srodek(Wektor3D sro)
Metoda ustawiająca wartość środka Umożliwia przypisanie Wektora3D środkowi bryły.
sro Wektor3D który przypisujemy środkowi
References srodek.
void Graniastoslup::ustaw_nazwa(std::string nazwa)
Metoda ustawiająca nazwę pliku Umożliwia przypisanie nazwy pliku.
nazwa nazwa pliku który chcemy przypisać
References nazwa_pliku.
Referenced by dron::dron.
Wektor3D Graniastoslup::pokaz_srodek() const
Metoda pokazująca wartość środka Umożliwia podgląd wartości środka.
Zwraca wektor3D środkowi.
References srodek.
Referenced by dron::pokaz_srodek, dron::przypisz_sciezke.
std::string Graniastoslup::pokaz_nazwa() const
Metoda pokazująca nazwę pliku Umożliwia podgląd nazwy pliku.
Zwraca string odpowiadający nazwie pliku.
References nazwa_pliku.
Referenced by dron::dron, dron::usun_drona.
void Graniastoslup::translacja(Wektor3D translacja)
Metoda przesuwająca graniastoslup o zadany wektor3D.
translacja Wektor3D odpowiadający przesunięciu
References srodek, wspol.
Referenced by dron::dron, dron::obrot, dron::obrot_rotorow, dron::przesuniecie, dron::ruch_pionowy.
void Graniastoslup::rotacja(Macierz3x3 obrot)
Metoda obracająca graniastoslup o zadaną Macierz3x3.
obrot Macierz3x3 odpowiadająca obrotowi
References srodek, wspol.
Referenced by dron::obrot, dron::obrot_rotorow, dron::przesuniecie, dron::ruch_pionowy.
void Graniastoslup::zapis()
Metoda zapisująca graniastoslup do pliku.
StrmPlikowy strumień dzięki któremy zapiszemy współrzędne punktów do pliku translacja_srodka Wektor3D który przesuwa środek bryły do góry i na dół żeby odpowiadały środkowi górnej i środkowi dolnej podstawy
References nazwa_pliku, srodek, wspol.
Referenced by dron::zapisz.