dron
double dron::kat
int dron::index
std::vector<Wektor3D> dron::sciezka
PzG::LaczeDoGNUPlota& dron::Lacze
Graniastoslup6 dron::rotor_orginal[4][4]
Graniastoslup6 dron::rotor[4][4]
Prostopadloscian dron::korpus_orginal
Prostopadloscian dron::korpus
Macierz3x3 dron::obr
Wektor3D dron::droga
dron::dron(int ind, PzG::LaczeDoGNUPlota &Lacze1, Wektor3D polozenie)
Konstruktor parametryczny klasy dron. Buduje drona i tworzy pliki w których będą zapisywanie punkty. Przypisuje dronowi jego index, tworzy Lacze oraz przestawia go o zadany wektor początkowy.
ind zmienna odpowiadająca indeksowi Lacze1 zmienna odpowiadająca laczy do gnuplota dzięki ktoremu tworzymy lacze polozenie wektor o jaki zostanie przestawiony dron wek wektor o który dodatkowo przesuwamy rotor aby nie był on częściowo zawarty w korpusie drona
References PzG::LaczeDoGNUPlota::DodajNazwePliku, Graniastoslup::pokaz_nazwa, Graniastoslup::translacja, Graniastoslup::ustaw_nazwa.
void dron::ruch_pionowy(double pion)
Metoda odpowiadająca za ruch pionowy Przesuwa drona w górę o wartość podaną przez zmienną pion.
pion mówi o ile ma przesunąć drona tmp Wektor3D pomocniczy
References Graniastoslup::rotacja, Graniastoslup::translacja.
Referenced by akcja.
void dron::przesuniecie(double droga)
Metoda odpowiadająca za przesuniecie drona w płaszczyźnie równoległej do płaszczyzny XY Przesuwa drona w płaszczyźnie XY o wartość podaną przez zmienną droga.
droga mówi o ile ma przesunąć drona tmp Wektor3D pomocniczy
References Graniastoslup::rotacja, Graniastoslup::translacja.
Referenced by akcja.
void dron::obrot(double kat_obrotu)
Metoda odpowiadająca za obrót drona Obraca drona o zadany kąt.
kat_obrotu mówi o ile ma obrócić dron radian kąt wyrażony w radianach
References Oblicz_Macierz_ObrotuZ, Graniastoslup::rotacja, StopienNaRadianZ, Graniastoslup::translacja.
Referenced by akcja.
void dron::obrot_rotorow()
Metoda odpowidająca za obrót rotorów.
tmp1 macierz przechowująca macierz obrotu tmp macierz obracająca rotory 1 i 3 tmp_v2 macierz obracajaca rotory 0 i 2 wek wektor o który dodatkowo przesuwamy rotor aby nie "uderzał" on w korpus drona przy obracaniu
References Oblicz_Macierz_ObrotuZ, Graniastoslup::rotacja, StopienNaRadianZ, Graniastoslup::translacja.
Referenced by akcja.
void dron::zapisz()
Metoda zapisujaca drona do plików.
References Graniastoslup::zapis.
Referenced by akcja.
void dron::akcja(char wybor)
Metoda odpowiadająca za porusanie się i animację drona.
wybor informacja jaką opcję wybrał użytkownik droga zmienna pomocnicza do której przypisywana jest droga kat zmienna do której użytkownik przypisuje kąt obrotu
References PzG::LaczeDoGNUPlota::DodajNazwePliku, Wektor< Templ_Typ_Wektor, Templ_Rozmiar_Wektor >::ilosc_stworzonych, Wektor< Templ_Typ_Wektor, Templ_Rozmiar_Wektor >::ilosc_tymczasowych, obrot, obrot_rotorow, przesuniecie, przypisz_sciezke, ruch_pionowy, PzG::LaczeDoGNUPlota::Rysuj, PzG::LaczeDoGNUPlota::UsunNazwePliku, zapisz.
void dron::przypisz_sciezke(double droga)
Metoda odpowiadjąca za budowę ścieżki lotu drona.
droga długość drogi
References Graniastoslup::pokaz_srodek.
Referenced by akcja.
Wektor3D dron::pokaz_srodek() const
Metoda zwracająca Wektor3D będący środkiem korpusu drona.
References Graniastoslup::pokaz_srodek.
void dron::usun_drona()
Metoda usuwająca drona z Lacza.
References Graniastoslup::pokaz_nazwa, PzG::LaczeDoGNUPlota::UsunNazwePliku.