PzG::LaczeDoGNUPlota
std::list<InfoPlikuDoRysowania> PzG::LaczeDoGNUPlota::_InfoPlikow_Glb
Lista nazw plików z danymi dla gnuplota.
Pole jest zarządcą listy nazw plików, z których są wczytywane dane dotyczące rysowania obrysu brył przez program gnuplot. Operacja ta wykonywana jest po wywołaniu polecenia. Pole to jest wspólne dla wszystkich łączy. Rysuj.
std::list<InfoPlikuDoRysowania> PzG::LaczeDoGNUPlota::_InfoPlikow_Lok
Lista nazw plików z danymi dla gnuplota.
Pole jest zarządcą listy nazw plików, z których są wczytywane dane dotyczące rysowania obrysu brył przez program gnuplot. Operacja ta wykonywana jest po wywołaniu polecenia. Pole to jest indywidulane dla danego łącza. Rysuj.
int PzG::LaczeDoGNUPlota::_Wejscie_GNUPlota
Deskryptor wejścia standardowego procesu gnuplota.
Pole przechowuje deskryptor wejścia standardowego związanego z procesem uruchomionego programu gnuplot.
int PzG::LaczeDoGNUPlota::_Wyjscie_GNUPlota
Deskryptor wejścia standardowego procesu gnuplota.
Pole przechowuje deskryptor do wyjścia standardowego związanego z procesem uruchomionego programu gnuplot.
bool PzG::LaczeDoGNUPlota::_WyswietlajKomunikatyOBledach
Decyduje czy mają być wyświetlane komunikaty o błędach.
Wartość tego pola decyduje o tym czy komunikaty o błędach będą wyświetlane na wyjście standardowe błędów (cerr), czy też nie. true - komunikaty będę wyświetlane, false - komunikaty nie będę wyświetlane.
Referenced by CzyWyswietlacKomunikaty.
std::string PzG::LaczeDoGNUPlota::_Preambula_RotacjaSkala
Zawiera zestaw poleceń, które muszą być wysłane do gnuplota przed rysowaniem.
Zawiera zestaw poleceń, które muszą być wysłane do gnuplota przed rysowaniem. Polecenia te dotyczą zmiany rotacji wokół osi OX i OZ oraz skali. Są one tworzone w momencie wywołania metod zmieniających te parametry.
TypTrybuRysowania PzG::LaczeDoGNUPlota::_TrybRys
Określa aktualny tryb rysowania.
Zawartość pola determinuje sposób rysowania, jaki zostanie wymuszony na programie gnuplot poprzez wysłanie do niego odpowiednich poleceń. Wspomniane wymuszenie jest realizowane poprzez wywołanie polecenia Rysuj()
Referenced by ZmienTrybRys, WezTrybRys.
float PzG::LaczeDoGNUPlota::_Xmin
Dolny zakres wyświetlanej skali skali dla osi OX.
Określa dolny zakres wyświetlanej skali dla osi OX.
Referenced by Xmin, UstawZakresX.
float PzG::LaczeDoGNUPlota::_Xmax
Górny zakres wyświetlanej skali skali dla osi OX.
Określa górny zakres wyświetlanej skali dla osi OX.
Referenced by Xmax, UstawZakresX.
float PzG::LaczeDoGNUPlota::_Ymin
Dolny zakres wyświetlanej skali skali dla osi OY.
Określa dolny zakres wyświetlanej skali dla osi OY.
Referenced by Ymin, UstawZakresY.
float PzG::LaczeDoGNUPlota::_Ymax
Górny zakres wyświetlanej skali skali dla osi OY.
Określa górny zakres wyświetlanej skali dla osi OY.
Referenced by Ymax, UstawZakresY.
float PzG::LaczeDoGNUPlota::_Zmin
Dolny zakres wyświetlanej skali skali dla osi OZ.
Określa dolny zakres wyświetlanej skali dla osi OZ.
Referenced by Zmin, UstawZakresZ.
float PzG::LaczeDoGNUPlota::_Zmax
Górny zakres wyświetlanej skali skali dla osi OZ.
Określa górny zakres wyświetlanej skali dla osi OZ.
Referenced by Zmax, UstawZakresZ.
float PzG::LaczeDoGNUPlota::_Xskala
Skala rysunku wzdłuż osi OX.
Wartość tego pola definiuje skalowanie rysunku wzdłuż osi OX (oś horyzontalna ekranu).
Referenced by SkalaX.
float PzG::LaczeDoGNUPlota::_Zskala
Skala rysunku wzdłuż osi OZ.
Wartość tego pola definiuje skalowanie rysunku wzdłuż osi OZ (oś wertykalna ekranu).
Referenced by SkalaZ.
float PzG::LaczeDoGNUPlota::_Xrotacja
Rotacja rysunku względem osi OX.
Wartość tego pola definiuje rotację rysunku (zmiane punktu patrzenia) względem osi OX.
Referenced by RotacjaX.
float PzG::LaczeDoGNUPlota::_Zrotacja
Rotacja rysunku względem osi OZ.
Wartość tego pola definiuje rotację rysunku (zmiane punktu patrzenia) względem osi OZ.
Referenced by RotacjaZ.
bool PzG::LaczeDoGNUPlota::_PokazOs_OX
Czy oś OX ma być widoczna.
Przechowuje informację decydującą o tym czy oś OX będzie widoczna na rysunku (true), czy też nie (false).
Referenced by PokazOs_OX.
bool PzG::LaczeDoGNUPlota::_PokazOs_OY
Czy oś OY ma być widoczna.
Przechowuje informację decydującą o tym czy oś OY będzie widoczna na rysunku (true), czy też nie (false).
Referenced by PokazOs_OY.
bool PzG::LaczeDoGNUPlota::DopiszPlikiDoPoleceniaRysowania(std::string &Polecenie, char const **Sep)
Tworzy listę parametrów umożliwiających rysowanie dodatkowych elementów.
Metoda ta przewidziana jest jako element rozszerzenia pozwalającego w klasach pochodnych powiększyć listę rysowanych elementów. Parametr Polecenie powinien zawierać polecenie plot lub splot, do którego będzie możliwe dopisanie dalszego ciągu. Polecenie - polecenie rysowania, do którego mają być dopisane nazwy plików i odpowiednie parametry dla polecenia plot. Sep - zawiera znak separatora między poszczególnymi parametrami. Jeżeli parametry listy przeszkód są generowane jako pierwsze, to zmienna ta musi być wskaźnikiem do wskaźnika na łańcuch: " ". true - operacja powiodła się, false - w przypadku przeciwnym.
std::string PzG::LaczeDoGNUPlota::ZapiszUstawienieZakresu(char Os) const
Tworzy polecenie ustawiające zakres dla danej współrzędnej.
Tworzy polecenie dla programu gnuplot ustawiające zakres współrzędnych wybranej współrzędnej x, y lub z, dla której ma być tworzony dany rysunek. Os - zawiera znak określający współrzędną, dla której ma zostać wygenerowane polecenie ustawienia zakresu. Łańcuch znaków polecenia ustawiającego żądany zakres dla wybranej współrzędnej.
std::string PzG::LaczeDoGNUPlota::ZapiszUstawienieRotacjiISkali() const
Tworzy polecenie ustawiające punkt obserwacji.
Tworzy polecenie dla programu gnuplot ustawiajające punkt obserwacji poprzez zadanie rotacji i skali dla poszczególnych osi. Napis będący utworzonym poleceniem dla programu gnuplot.
bool PzG::LaczeDoGNUPlota::PrzeslijDoGNUPlota(const char *Polecenie)
Przesyła polecenie do gnuplota.
Przesyła na wejście programu gnuplot zadany ciąg znaków. Polecenie - komunikat przeznaczony do przeslania. Musi być zainicjowane połączenie z programem gnuplot. true - jesli przeslanie polecenia zakończyło się powodzeniem, false - w przypadku przeciwnym.
bool PzG::LaczeDoGNUPlota::CzyWyswietlacKomunikaty() const
Udostępnia informację czy mają być wyświetlane informacje o błędach.
Udostępnia wartość pola _WyswietlajKomunikatyOBledach. Określa ono, czy mają być wyświetlane komunikaty o błędach na wyjście standardowe, czy też nie. true - komunikaty mają być wyswietlane na wejściu standard error. false - komunikaty nie mają być wyświetlane.
References _WyswietlajKomunikatyOBledach.
bool PzG::LaczeDoGNUPlota::UtworzProcesPotomny()
Uruchamia program gnuplot jako proces potomny.
Uruchamia program gnuplot jako proces potomny. true - jeśli operacja powiodła się. false - w przypadku przeciwnym.
void PzG::LaczeDoGNUPlota::KomunikatBledu(const char *sKomunikat) const
Wyświetla komunika błędu.
Wyświetla na wyjście "standard error" komunikat (przekazany jako parametr), o ile pole _WyswietlajKomunikatyOBledach ma wartość true. W przypadku przeciwnym komunikat nie jest wyświetlany. sKomunikat - treść komunikatu, który ma być wyświetlony.
void PzG::LaczeDoGNUPlota::BudujPreambulePoleceniaRysowania(std::string &Preambula)
Tworzy preambułę poprzedzającą polecenie rysowania.
Tworzy zbiór poleceń, które ustawiają właściwy tryb rysowania oraz zakresy współrzędnych, jak też wszystkie inne parametry wynikające z przyjętego trybu rysowania. Preambula - zawiera treść stworzonej preambuły.
void PzG::LaczeDoGNUPlota::BudujPreambule_2D(std::string &Preambula)
Tworzy preambułę poprzedzającą polecenie rysowania w trybie 2D.
Tworzy zbiór poleceń, które ustawiają właściwy tryb rysowania oraz zakresy współrzędnych, jak też wszystkie inne parametry wynikające z trybu rysowania 2D. Preambula - zawiera treść stworzonej preambuły.
void PzG::LaczeDoGNUPlota::BudujPreambule_3D(std::string &Preambula)
Tworzy preambułę poprzedzającą polecenie rysowania w trybie 3D.
Tworzy zbiór poleceń, które ustawiają właściwy tryb rysowania oraz zakresy współrzędnych, jak też wszystkie inne parametry wynikające z trybu rysowania 3D. Preambula - zawiera treść stworzonej preambuły.
void PzG::LaczeDoGNUPlota::PokazOs_OX(bool Pokaz)
Umożliwia lub zabrania rysowania osi OX.
Umożliwia lub zabrania rysowania osi OX na rysunku wykresu. Pokaz - decyduje o tym czy oś OX będzie rysowana (true), czy też nie (false).
References _PokazOs_OX.
bool PzG::LaczeDoGNUPlota::PokazOs_OX() const
Czy oś OX ma być rysowana.
Udostępnia informację czy oś OX ma być rysowana, czy też nie. true - gdy oś OX ma być rysowana, false - w przypadku przeciwnym.
References _PokazOs_OX.
void PzG::LaczeDoGNUPlota::PokazOs_OY(bool Pokaz)
Umożliwia lub zabrania rysowania osi OY.
Umożliwia lub zabrania rysowania osi OY na rysunku wykresu. Pokaz - decyduje o tym czy oś OY będzie rysowana (true), czy też nie (false).
References _PokazOs_OY.
bool PzG::LaczeDoGNUPlota::PokazOs_OY() const
Czy oś OY ma być rysowana.
Udostępnia informację czy oś OY ma być rysowana, czy też nie. true - gdy oś OY ma być rysowana, false - w przypadku przeciwnym.
References _PokazOs_OY.
float PzG::LaczeDoGNUPlota::Xmin() const
Dolna wartość zakresu dla osi OX.
Udostępnia dolną wartość zakresu skali wzdłuż osi OX. Dolną wartość zakresu skali wzdłuż osi OX.
References _Xmin.
float PzG::LaczeDoGNUPlota::Xmax() const
Górną wartość zakresu dla osi OX.
Udostępnia górną wartość zakresu skali wzdłuż osi OX. Górną wartość zakresu skali wzdłuż osi OX.
References _Xmax.
float PzG::LaczeDoGNUPlota::Ymin() const
Dolną wartość zakresu dla osi OY.
Udostępnia dolną wartość zakresu skali wzdłuż osi OY. Dolną wartość zakresu skali wzdłuż osi OY.
References _Ymin.
float PzG::LaczeDoGNUPlota::Ymax() const
Górną wartość zakresu dla osi OY.
Udostępnia górną wartość zakresu skali wzdłuż osi OY. Górną wartość zakresu skali wzdłuż osi OY.
References _Ymax.
float PzG::LaczeDoGNUPlota::Zmin() const
Dolną wartość zakresu dla osi OZ.
Udostępnia dolną wartość zakresu skali wzdłuż osi OZ. Dolną wartość zakresu skali wzdłuż osi OZ.
References _Zmin.
float PzG::LaczeDoGNUPlota::Zmax() const
Górną wartość zakresu dla osi OZ.
Udostępnia górną wartość zakresu skali wzdłuż osi OZ. Górną wartość zakresu skali wzdłuż osi OZ.
References _Zmax.
void PzG::LaczeDoGNUPlota::ZmienTrybRys(TypTrybuRysowania Tryb)
Zmienia tryb rysowania.
Zmienia tryb rysowania jaki zostanie wymuszony na programie gnuplot. Tryb - wartość parametru określa nowy tryb rysowania.
References _TrybRys.
Referenced by Scena::Scena.
TypTrybuRysowania PzG::LaczeDoGNUPlota::WezTrybRys() const
Udostępnia aktualny tryb rysowania.
Udostępnia informację o aktualnym trybie rysowania. Informacja o aktualnym trybie rysowania.
References _TrybRys.
void PzG::LaczeDoGNUPlota::UstawZakresX(float Xo, float Xn)
Ustawia zakres osi OX.
Ustawia zakres osi OX. Ogranicza to obszar, który będzie zwizualizowany przez programa gnuplot. Xo - dolna granica obszaru rysowania dla osi OX. Xn - górna granica obszaru rysowania dla osi OX.
References _Xmax, _Xmin.
Referenced by Scena::Scena.
void PzG::LaczeDoGNUPlota::UstawZakresY(float Yo, float Yn)
Ustawia zakres osi OY.
Ustawia zakres osi OY. Ogranicza to obszar, który będzie zwizualizowany przez programa gnuplot. Yo - dolna granica obszaru rysowania dla osi OY. Yn - górna granica obszaru rysowania dla osi OY.
References _Ymax, _Ymin.
Referenced by Scena::Scena.
void PzG::LaczeDoGNUPlota::UstawZakresZ(float Zo, float Zn)
Ustawia zakres osi OZ.
Ustawia zakres osi OZ. Ogranicza to obszar, który będzie zwizualizowany przez programa gnuplot. Zo - dolna granica obszaru rysowania dla osi OZ. Zn - górna granica obszaru rysowania dla osi OZ.
References _Zmax, _Zmin.
Referenced by Scena::Scena.
float PzG::LaczeDoGNUPlota::SkalaX() const
Udostępnia skalę dla osi OX.
Udostępnia skalę dla osi OX dla tworzonego rysunku. Skala dla osi OX.
References _Xskala.
float PzG::LaczeDoGNUPlota::SkalaZ() const
Udostępnia skalę dla osi OZ.
Udostępnia skalę dla osi OZ dla tworzonego rysunku. Skala dla osi OZ.
References _Zskala.
void PzG::LaczeDoGNUPlota::UstawSkaleX(float skala_x)
Zadaje skalę wzdłuż osi OZ.
Zadaje skalę wzdłuż osi OX dla tworzonego rysunku. skala_x - skala wzdłuż osi OX.
void PzG::LaczeDoGNUPlota::UstawSkaleZ(float skala_z)
Zadaje skalę wzdłuż osi OZ.
Zadaje skalę wzdłuż osi OZ dla tworzonego rysunku. skala_z - skala wzdłuż osi OZ.
void PzG::LaczeDoGNUPlota::UstawSkaleXZ(float skala_x, float skala_z)
Zadaje skalę wzdłuż osi OX i OZ.
Zadaje skalę wzdłuż osi OX i OZ dla tworzonego rysunku. skala_x - skala wzdłuż osi OX. skala_z - skala wzdłuż osi OZ.
Referenced by Scena::Scena.
float PzG::LaczeDoGNUPlota::RotacjaX() const
Wartość kąta rotacji względem osi OX.
Udostępnia wartość kąta rotacji renderowanego rysunku wokół osi OX. Zwracana wartość wyrażona jest w stopiniach. Wyrażona w stopniach wartość kąta rotacji wokół osi OX.
References _Xrotacja.
float PzG::LaczeDoGNUPlota::RotacjaZ() const
Wartość kąta rotacji względem osi OZ.
Udostępnia wartość kąta rotacji renderowanego rysunku wokół osi OZ. Zwracana wartość wyrażona jest w stopiniach. Wyrażona w stopniach wartość kąta rotacji wokół osi OZ.
References _Zrotacja.
void PzG::LaczeDoGNUPlota::UstawRotacjeX(float KatX_st)
Ustawia rotację wokół osi OX.
Zadaje kąt rotacji wokół osi OX. Umożliwia to zmianę punktu obserwacji renderowanego rysunku. KatX_st - wartość kąta rotacji. Jego wartość podawana jest w stopniach. Dopuszczalne wartości mieszczą się w zakresie [-360,360]. Wartości spoza tego zakresu mogą powodować nieprawidłowe ustawienie punktu obserwacji.
void PzG::LaczeDoGNUPlota::UstawRotacjeZ(float KatZ_st)
Ustawia rotację wokół osi OZ.
Zadaje kąt rotacji wokół osi OZ. Umożliwia to zmianę punktu obserwacji renderowanego rysunku. KatZ_st - wartość kąta rotacji. Jego wartość podawana jest w stopniach. Dopuszczalne wartości mieszczą się w zakresie [-360,360]. Wartości spoza tego zakresu mogą powodować nieprawidłowe ustawienie punktu obserwacji.
void PzG::LaczeDoGNUPlota::UstawRotacjeXZ(float KatX_st, float KatZ_st)
Ustawia rotację wokół osi OX i OZ.
Zadaje jednocześnie kąt rotacji wokół osi OX i OZ. Umożliwia to zmianę punktu obserwacji renderowanego rysunku. KatX_st - wartość kąta rotacji względem osi OX. Jego wartość podawana jest w stopniach. KatZ_st - wartość kąta rotacji względem osi OZ. Jego wartość podawana jest w stopniach.
Referenced by Scena::Scena.
void PzG::LaczeDoGNUPlota::WyswietlajKomunikatyBledow(bool WyswietlajKomunikaty=true)
Zezwala lub zabrania wyświetlania komunikatów.
Metoda pozwala, albo też zabrania wyświetlania komunikatów o blędach. Jeżeli jakaś z operacji nie powiedzie się, to jako wynik zwracana jest wartość false. Oprócz tego metody takie moga wyświetlać komunikaty, które kierowane są na wyjście "standard error" Domyślnie przymuje się, że programista nie chce, aby wyświetlały się dodatkwe komunikaty. Wywołując tę metodę można to zmienić. WyswietlajKomunikaty - wartość parametru zostaje zapamiętana. Jeśli jest ona true (domyślna wartość parametru), to komunikaty będą wyświetlane. Gdy jest ona false, to komunikaty nie będą wyświetlane.
InfoPlikuDoRysowania& PzG::LaczeDoGNUPlota::DodajNazwePliku(const char *sNazwaPliku, bool SprawdzIstnienie=false, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Dodaje nazwę pliku.
Powoduje dodanie do listy plików zawierajacych dane dla gnuplota, nowej nazwy pliku. sNazwaPliku - nazwa pliku z danymi dla gnuplota. SprawdzIstnienie - decyduje o tym czy będzie sprawdzane istnienie danego pliku w momencie wywołania niniejszej metody. Dostep - decyduje o tym, czy dany plik będzie widziany przez wszystkie łącza, czy też przez tylko jedno. Parametr ten ma znaczenie tylko wtedy, gdy programista chce aby ukazało się więcej niż jedno okienko programu gnuplot. Oznacza to uruchmienie tylu procesów programu gnuplot ile jest okienek. Parametr Dostep decyduje wówczas, czy dane zawarte w pliku będą wyświetlane w jednym okienku, czy też we wszystkich. Zwraca referencję do obiektu zawierającego atrybuty rysowania danych w podanym pliku.
Referenced by dron::akcja, dron::dron, Scena::dzialanie, Scena::Scena.
InfoPlikuDoRysowania& PzG::LaczeDoGNUPlota::DodajNazwePliku_Lamana(const char *sNazwaPliku, bool SprawdzIstnienie=false, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Dodaje nazwę pliku.
Powoduje dodanie do listy plików zawierajacych dane dla gnuplota, nowej nazwy pliku. Domyślnie dane z tego pliku będą rysowane jako łamana łącząca punkty o podanych współrzędnych. sNazwaPliku - nazwa pliku z danymi dla gnuplota. SprawdzIstnienie - decyduje o tym czy będzie sprawdzane istnienie danego pliku w momencie wywołania niniejszej metody. Dostep - decyduje o tym, czy dany plik będzie widziany przez wszystkie instancje łącza, czy też przez tylko jedno. Parametr ten ma znaczenie tylko wtedy, gdy programista chce aby ukazało się więcej niż jedno okienko programu gnuplot. Oznacza to uruchmienie tylu procesów programu gnuplot ile jest okienek. Parametr Dostep decyduje wówczas, czy dane zawarte w pliku będą wyświetlane w jednym okienku, czy też we wszystkich. Zwraca referencję do obiektu zawierającego atrybuty rysowania danych w podanym pliku.
InfoPlikuDoRysowania& PzG::LaczeDoGNUPlota::DodajNazwePliku_JednakowePunkty(const char *sNazwaPliku, bool SprawdzIstnienie=false, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Dodaje nazwę pliku.
Powoduje dodanie do listy plików zawierajacych dane dla gnuplota, nowej nazwy pliku. Domyślnie dane z tego pliku będą rysowane jako zbiór jednakowych punktów o podanych współrzędnych. sNazwaPliku - nazwa pliku z danymi dla gnuplota. SprawdzIstnienie - decyduje o tym czy będzie sprawdzane istnienie danego pliku w momencie wywołania niniejszej metody. Dostep - decyduje o tym, czy dany plik będzie widziany przez wszystkie instancje łącza, czy też przez tylko jedno. Parametr ten ma znaczenie tylko wtedy, gdy programista chce aby ukazało się więcej niż jedno okienko programu gnuplot. Oznacza to uruchmienie tylu procesów programu gnuplot ile jest okienek. Parametr Dostep decyduje wówczas, czy dane zawarte w pliku będą wyświetlane w jednym okienku, czy też we wszystkich. Zwraca referencję do obiektu zawierającego atrybuty rysowania danych w podanym pliku.
InfoPlikuDoRysowania& PzG::LaczeDoGNUPlota::DodajNazwePliku_PunktyRoznejWielkosci(const char *sNazwaPliku, bool SprawdzIstnienie=false, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Dodaje nazwę pliku.
Powoduje dodanie do listy plików zawierajacych dane dla gnuplota, nowej nazwy pliku. sNazwaPliku - nazwa pliku z danymi dla gnuplota. SprawdzIstnienie - decyduje o tym czy będzie sprawdzane istnienie danego pliku w momencie wywołania niniejszej metody. Dostep - decyduje o tym, czy dany plik będzie widziany przez wszystkie instancje łącza, czy też przez tylko jedno. Parametr ten ma znaczenie tylko wtedy, gdy programista chce aby ukazało się więcej niż jedno okienko programu gnuplot. Oznacza to uruchmienie tylu procesów programu gnuplot ile jest okienek. Parametr Dostep decyduje wówczas, czy dane zawarte w pliku będą wyświetlane w jednym okienku, czy też we wszystkich. Zwraca referencję do obiektu zawierającego atrybuty rysowania danych w podanym pliku.
const InfoPlikuDoRysowania* PzG::LaczeDoGNUPlota::ZnajdzNazwePliku(const char *sNazwaPliku, TypDostepuDoZasobu Dostep=DZ_Lokalny) const
Znajduje obiekt przechowujący nazwę pliku z danymi do rysowania.
Referenced by ZnajdzNazwePliku.
const InfoPlikuDoRysowania* PzG::LaczeDoGNUPlota::ZnajdzNazwePliku(const std::string &NazwaPliku, TypDostepuDoZasobu Dostep=DZ_Lokalny) const
Znajduje obiekt przechowujący nazwę pliku z danymi do rysowania.
Odszukuje strukturę zawierającą nazwę pliku, w którym powinny być zapisane współrzędne punktów do rysunku odpowiedniej łamanej lub powierzchni (w zależności od wcześniejszego wyboru trybu rysowania - patrz metoda ZmienTrybRys()). NazwaPliku - nazwa pliku, dla którego ma zostać odnaleziony obiekt zawierające dane określające sposób rysowania łamanej lub powierzchni. Dostep - decyduje o tym, czy dany plik będzie szukany wsród plików, które mają być widziane przez wszystkie instancje programu gnuplot, czy też pośród tych, które są widoczne tylko przez tą instancję, dla której wywołana zostaje ta metoda. Domyślnie przyjmuje się ten drugi wariant. Jeżeli w liście nazw plików z danymi dla gnuplota zostanie znaleziony obiekt, który zawiera identyczną nazwę, jak ta przekazana przez parametr sNazwaPliku, to metoda zwraca wskaźnik do tego obiektu. Jest on zwracany w trybie tylko do odczytu. W przypadku przecinym zwracany jest wskaźnik nullptr.
References ZnajdzNazwePliku.
InfoPlikuDoRysowania* PzG::LaczeDoGNUPlota::ZnajdzNazwePliku(const char *sNazwaPliku, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Znajduje obiekt przechowujący nazwę pliku z danymi do rysowania.
Odszukuje strukturę zawierającą nazwę pliku, w którym powinny być zapisane współrzędne punktów do rysunku odpowiedniej łamanej lub powierzchni (w zależności od wcześniejszego wyboru trybu rysowania - patrz metoda ZmienTrybRys()). sNazwaPliku - nazwa pliku, dla którego ma zostać odnaleziony obiekt zawierające dane określające sposób rysowania łamanej lub powierzchni. Dostep - decyduje o tym, czy dany plik będzie szukany wsród plików, które mają być widziane przez wszystkie instancje programu gnuplot, czy też pośród tych, które są widoczne tylko przez tą instancję, dla której wywołana zostaje ta metoda. Domyślnie przyjmuje się ten drugi wariant. Jeżeli w liście nazw plików z danymi dla gnuplota zostanie znaleziony obiekt, który zawiera identyczną nazwę, jak ta przekazana przez parametr sNazwaPliku, to metoda zwraca wskaźnik do tego obiektu. Jest on zwracany w trybie do modyfikacji. W przypadku przecinym zwracany jest wskaźnik nullptr.
References ZnajdzNazwePliku.
InfoPlikuDoRysowania* PzG::LaczeDoGNUPlota::ZnajdzNazwePliku(const std::string &NazwaPliku, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Znajduje obiekt przechowujący nazwę pliku z danymi do rysowania.
Odszukuje strukturę zawierającą nazwę pliku, w którym powinny być zapisane współrzędne punktów do rysunku odpowiedniej łamanej lub powierzchni (w zależności od wcześniejszego wyboru trybu rysowania - patrz metoda ZmienTrybRys()). NazwaPliku - nazwa pliku, dla którego ma zostać odnaleziony obiekt zawierające dane określające sposób rysowania łamanej lub powierzchni. Dostep - decyduje o tym, czy dany plik będzie szukany wsród plików, które mają być widziane przez wszystkie instancje programu gnuplot, czy też pośród tych, które są widoczne tylko przez tą instancję, dla której wywołana zostaje ta metoda. Domyślnie przyjmuje się ten drugi wariant. Jeżeli w liście nazw plików z danymi dla gnuplota zostanie znaleziony obiekt, który zawiera identyczną nazwę, jak ta przekazana przez parametr sNazwaPliku, to metoda zwraca wskaźnik do tego obiektu. Jest on zwracany w trybie do modyfikacji. W przypadku przecinym zwracany jest wskaźnik nullptr.
References ZnajdzNazwePliku.
bool PzG::LaczeDoGNUPlota::UsunNazwePliku(const InfoPlikuDoRysowania *wInfoPliku, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Usuwa z listy nazw plików z danymi do rysowania usuwa wybraną nazwę.
Referenced by dron::akcja, Scena::dzialanie, dron::usun_drona.
bool PzG::LaczeDoGNUPlota::UsunNazwePliku(const char *sNazwaPliku, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Usuwa z listy nazw plików z danymi do rysowania usuwa wybraną nazwę.
bool PzG::LaczeDoGNUPlota::UsunNazwePliku(const std::string &NazwaPliku, TypDostepuDoZasobu Dostep=DZ_Lokalny)
Usuwa z listy nazw plików z danymi do rysowania usuwa wybraną nazwę.
bool PzG::LaczeDoGNUPlota::DopiszRysowanieZPlikow(std::string &Polecenie, char const **Sep)
Tworzy listę parametrów umożliwiających rysowanie brył z plików.
bool PzG::LaczeDoGNUPlota::DopiszRysowanieZRoznychPunktow(std::string &Polecenie, char const *Sep)
Tworzy listę parametrów umożliwiających rysowanie brył z plików.
bool PzG::LaczeDoGNUPlota::CzyPolaczenieJestZainicjowane() const
Informuje, czy połączenie z gnuplot'em jest zainicjalizowane.
Informuje, czy połączenie z programem gnuplot jest zainicjowane. true - jeśli tak, false - w przypadku przeciwnym.
bool PzG::LaczeDoGNUPlota::Rysuj()
Generuje polecenie rysowania i przesyła je do gnuplota.
Jeżeli lista plików nie jest pusta, to generuje sekwencje poleceń dla programu gnuplot mająca na celu narysowanie płaszczyzn na na podstawie danych zawartych w plikach z listy. Lista plików nie powinna być pusta. Nazwy plików na niej można umieścić za pomoca metody DodajNazwePliku jak też innych tego typu metod. Metoda nie wymaga wcześniejszego zainicjowania połączenia z gnuplotem. true - gdy zostają poprawnie wysłane polecenia dla gnuplota. Nie oznacza to jednak, że proces rysowania zakończył się pomyślnie. false - gdy połączenie z gnuplotem nie może zostać poprawnie zainicjalizowane lub gdy lista plików jest pusta.
Referenced by dron::akcja, Scena::dzialanie, Scena::Scena.
bool PzG::LaczeDoGNUPlota::RysujDoPliku(const char *sNazwaPliku)
Generuje polecenie rysowania do pliku i przesyła je do gnuplota.
Działa analogicznie jak metoda Rysuj, z tą różnicą, że rysunek robota składowany jest w pliku o nazwie przekazanej przez parametr NazwaPliku. Rysunek jest zapisywany w formacie PNG. Lista plików nie powinna być pusta ponadto powinno być możliwe otwarcie do zapisu pliku o nazwie przekazanej przez parametr NazwaPliku, do której dołączane jest rozszerzenie .ps . Metoda nie wymaga wcześniejszego zainicjowania połączenia z programem gnuplot. sNazwaPliku - nazwa pliku, w którym ma być zapisny rysunek tworzony przez gnuplot. true - gdy zostają poprawnie wysłane polecenia dla gnuplota. Nie oznacza to jednak, że proces rysowania zakończył się pomyślnie. false - gdy połączenie z gnuplotem nie może zostać poprawnie zainicjalizowane lub gdy lista plików jest pusta lub też gdy nie można otworzyć pliku do zapisu.
bool PzG::LaczeDoGNUPlota::Inicjalizuj()
Inicjalizuje połączenie z programem gnuplot.
Inicjalizuje połączenie z programem gnuplot. Realizowane jest to poprzez rozwidlenie procesu i uruchomienie jako procesu potomnego programu gnuplot. Komunikacja z programem gnuplot realizowana jest poprzez przejęcie jego wejścia i wyjścia standardowego. true - gdy połączenie z programem 0gnuplot zostało poprawnie zainicjalizowane lub gdy już wcześniej było zainicjalizowane. false - gdy proces inicjalizacji połączenia zakończył się niepowodzeniem.
Referenced by Scena::Scena.
void PzG::LaczeDoGNUPlota::UsunOstatniaNazwe_ListaLokalna()
Usuwa ostatnią nazwę pliku.
Usuwa ostatnią nazwę z lokalnej listy nazw plików, tzn. listy, która jest widoczna tylko w danym łączu z programem gnuplot.
void PzG::LaczeDoGNUPlota::UsunOstatniaNazwe_ListaGlobalna()
Usuwa ostatnią nazwę pliku.
Usuwa ostatnią nazwę z globalnej listy nazw plików, tzn. listy, która jest widoczna we wszystkich łączach z programem gnuplot.
void PzG::LaczeDoGNUPlota::UsunWszystkieNazwyPlikow()
Kasuje zawartość listy nazw plików.
Calkowicie kasuje zawartość listy nazw plików.
PzG::LaczeDoGNUPlota::LaczeDoGNUPlota()
virtual PzG::LaczeDoGNUPlota::~LaczeDoGNUPlota()