Macierz.hh
typedef Macierz<double, 3> Macierz3x3
Deklaracja Macierzy3x3 Deklaracja macierzy 3D.
std::istream& operator>>(std::istream &in, Macierz< Templ_Typ, Templ_Rozmiar > &mat)
Przeciążenie operatora strumieniowego in dla macierzy. Umożliwia bezpośredie wczytanie macierzy.
in strumień wejściowy mat macierz odpowiadająca wczytywanej macierzy Zwraca strumień wejściowy in.
std::ostream& operator<<(std::ostream &out, Macierz< Templ_Typ, Templ_Rozmiar > const &mat)
Przeciążenie operatora strumieniowego out dla macierzy. Umożliwia bezpośredie wyświetlenie macierzy.
out strumień wyjściowy mat macierz odpowiadająca wyświetlaniej macierzy Zwraca strumień wyjściowy out.
double StopienNaRadianX(double kat_stopnieX)
Zamaina stopni na radian 3D wokół OX. Funkcja zamieniająca wartość stopni na stopnie w radianach, aby umożliwić obrót 3D wokół osi OX.
double StopienNaRadianY(double kat_stopnieY)
Zamaina stopni na radian 3D wokół OY. Funkcja zamieniająca wartość stopni na stopnie w radianach, aby umożliwić obrót 3D wokół osi OY.
double StopienNaRadianZ(double kat_stopnieZ)
Zamaina stopni na radian 3D wokół OZ. Funkcja zamieniająca wartość stopni na stopnie w radianach, aby umożliwić obrót 3D wokół osi OZ.
Referenced by dron::obrot, dron::obrot_rotorow.
void Oblicz_Macierz_ObrotuX(double kat_radianX, Macierz3x3 &Mac)
Funkcja obliczająca macierz obrotu 3D OX. Funkcja umożliwiająca obliczenie macierzy obrotu umożliwiającej obrót 3D wokół osi OX.
void Oblicz_Macierz_ObrotuY(double kat_radianY, Macierz3x3 &Mac)
Funkcja obliczająca macierz obrotu 3D OY. Funkcja umożliwiająca obliczenie macierzy obrotu umożliwiającej obrót 3D wokół osi OY.
void Oblicz_Macierz_ObrotuZ(double kat_radianZ, Macierz3x3 &Mac)
Funkcja obliczająca macierz obrotu 3D OZ. Funkcja umożliwiająca obliczenie macierzy obrotu umożliwiającej obrót 3D wokół osi OZ.
Referenced by dron::obrot, dron::obrot_rotorow.